name: dchalky
description:  A simple and elegant way to add colors and styles to your Dart/Flutter console logs, inspired by Chalk.js
version: 0.0.1
homepage: https://github.com/neryad/dart_chalk.git
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0